class Alphabet_dict:
    actor = {"A": "ACTOR", "a": "ACTOR",
         "B": "BAKER", "b": "BAKER",
         "C": "CANTEEN", "c": "CANTEEN",
         "D": "DIVER", "d": "DIVER",
         "E": "EAGLE", "e": "EAGLE",
         "F": "FISHER", "f": "FISHER",
         "G": "GANGWAY", "g": "GANGWAY",
         "H": "HALLIARD", "h": "HALLIARD",
         "I": "INSECT", "i": "INSECT",
         "J": "JACKEY", "j": "JACKEY",
         "K": "KNAPSACK", "k": "KNAPSACK",
         "L": "LUGGER", "l": "LUGGER",
         "M": "MUSKET", "m": "MUSKET",
         "N": "NEPTUNE", "n": "NEPTUNE",
         "O": "OYSTER", "o": "OYSTER",
         "P": "PISTOL", "p": "PISTOL",
         "Q": "QUADRANT", "q": "QUADRANT",
         "R": "REEFER", "r": "REEFER",
         "S": "SHIPMATE", "s": "SHIPMATE",
         "T": "TOPSAIL", "t": "TOPSAIL",
         "U": "UNLOAD", "u": "UNLOAD",
         "V": "VESSEL", "v": "VESSEL",
         "W": "WINDAGE", "w": "WINDAGE",
         "X": "X-RAY", "x": "X-RAY",
         "Y": "YEOMAN", "y": "YEOMAN",
         "Z": "ZEBRA", "z": "ZEBRA",
         "1": "ONE", "2": "TWO", "3": "THREE", "4": "FOUR", "5": "FIVE",
         "6": "SIX", "7": "SEVEN", "8": "EIGHT", "9": "NINE", "0": "ZERO"
        }

    alpha = {"A": "ALPHA", "a": "ALPHA",
         "B": "BRAVO", "b": "BRAVO",
         "C": "CHARLIE", "c": "CHARLIE",
         "D": "DELTA", "d": "DELTA",
         "E": "ECHO", "e": "ECHO",
         "F": "FOXTROT", "f": "FOXTROT",
         "G": "GOLF", "g": "GOLF",
         "H": "HOTEL", "h": "HOTEL",
         "I": "INDIA", "i": "INDIA",
         "J": "JULIET", "j": "JULIET",
         "K": "KILO", "k": "KILO",
         "L": "LIMA", "l": "LIMA",
         "M": "MIKE", "m": "MIKE",
         "N": "NOVEMBER", "n": "NOVEMBER",
         "O": "OSCAR", "o": "OSCAR",
         "P": "PAPA", "p": "PAPA",
         "Q": "QUEBEC", "q": "QUEBEC",
         "R": "ROMEO", "r": "ROMEO",
         "S": "SIERRA", "s": "SIERRA",
         "T": "TANGO", "t": "TANGO",
         "U": "UNIFORM", "u": "UNIFORM",
         "V": "VICTOR", "v": "VICTOR",
         "W": "WHISKEY", "w": "WHISKEY",
         "X": "X-RAY", "x": "X-RAY",
         "Y": "YANKEE", "y": "YANKEE",
         "Z": "ZULU", "z": "ZULU",
         "1": "ONE", "2": "TWO", "3": "THREE", "4": "FOUR", "5": "FIVE",
         "6": "SIX", "7": "SEVEN", "8": "EIGHT", "9": "NINE", "0": "ZERO"
        }

        
        
